### ISSUE TITLE
Improve service traffic table on mobile

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1031]
Two issues:

* It's not clear where each row ends in the mobile layout. They run together.
* The arrows should be hidden or changed to down arrows like we do for pipelines.

Screenshot:

![screen shot 2016-12-13 at 10 20 00 am](https://cloud.githubusercontent.com/assets/1167259/21145880/cdffb27c-c11d-11e6-8fe3-76daf7d70f32.png)

**Comment by spadgett** [comment]
Also seems to be an extra table cell at the bottom.

**Comment by juanvallejo** [comment]
@spadgett 
> It's not clear where each row ends in the mobile layout. They run together.

Hm, this seems to be happening because the [traffic-table directive](https://github.com/openshift/origin-web-console/blob/master/app/views/directives/traffic-table.html#L18) has the `ng-repeat` attribute on the `<tr>` tag rather than on the `<tbody>`. [pods-table](https://github.com/openshift/origin-web-console/blob/master/app/views/directives/pods-table.html#L15) and `app/views/browse/routes.html` both have `ng-repeat` on the `<tbody>`.

cc @jwforres
