### ISSUE TITLE
Help / User navbar dropdowns only support "dom" type, not "link"

### ISSUE THREAD

**Issue by jawnsy** [openshift/origin-web-console#1077]
The examples on [Web Console Customization](https://docs.openshift.org/latest/install_config/web_console_customization.html#top-navigation-dropdown-menus) all show the `dom` method, but skip over the convenience types like `link`, even where they may make more sense.

For example, this:

```javascript
{
  type: 'dom',
  node: '<li><a href="http://www.example.com/report" target="_blank">Report a Bug</a></li>'
}
```

looks like it's equivalent to (from the [angular-extension-registry](https://github.com/openshift/angular-extension-registry#built-in-types) README):

```javascript
{
  type: 'link',
  linkText: 'Report a Bug',
  href: 'http://www.example.com/report',
  target: '_blank'
}
```

However, this doesn't actually work at the moment, presumably because we have `extension-types="dom html"` defined.  For simple cases like this, it would be nice to have the ability to specify that we want a link or a divider, instead of specifying HTML.

**Comment by benjaminapetersen** [comment]
Great, thanks!  Our initial use of the extension framework was restrictive (though type 'dom' lets you render all kinds of things...so maybe not), hoping we'd generate some use cases & add as requested.

**Comment by benjaminapetersen** [comment]
@jwforres

**Comment by jwforres** [comment]
No I dont see us changing this one, link doesn't work in this context, you can't put a link node directly under where the extension is defined. The extension is intentionally defined where it is because these dropdowns require li elements for each item.  To do what you want we would have to add specialized logic to the extension registry to somehow understand this and that isnt realistically going to happen.

**Comment by jawnsy** [comment]
Fair enough, thanks for your consideration :)
