### ISSUE TITLE
Env var values from secrets or configmaps do not display properly on next steps page

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#1117]
![screen shot 2017-01-16 at 10 00 30 am](https://cloud.githubusercontent.com/assets/895728/21987805/e728dace-dbd2-11e6-8609-c88e248dd9ae.PNG)

@benjaminapetersen, any ideas?  The ['altTextForValueFrom' filter is in use](https://github.com/openshift/origin-web-console/blob/master/app/scripts/controllers/create/nextSteps.js#L60)...

**Comment by benjaminapetersen** [comment]
Looking @ this one next.

**Comment by benjaminapetersen** [comment]
This doesn't seem to be a key value editor display bug, because these are legitimate template params w/o values.  Currently, kve is set to `entries="parameters.all"`.   Some of these parameters have undefined values at this point, others are probably related to objects yet to be created.

@jwforres @spadgett ping just to confirm as I close this.

**Comment by jwforres** [comment]
yeah these are template params not env vars, they are never going to have valueFrom set
