### ISSUE TITLE
Make clear that `edit-command` take only single command

### ISSUE THREAD

**Issue by jhadvig** [openshift/origin-web-console#1192]
Based on [issue](https://github.com/openshift/origin/issues/12681), where user misunderstood the concept of `edit-command` directive and wants to put multiple commands. Would good to make it more clear that those fields take single cmd and its arguments, by either updating the help-text under the directive or make the argument fields style different. But I guess updating the help-text should be sufficient.
@spadgett @rhamilto @jwforres thoughts ?

**Comment by spadgett** [comment]
Wonder if it shouldn't be just be a plain input by default with an advanced mode if you need to enter arguments with spaces or multiple lines. Here is a CLI example for reference:

```
$ oc set deployment-hook dc/frontend --pre -c helloworld -e CUSTOM_VAR1=custom_value1 \
  -v data --failure-policy=abort -- /usr/bin/command arg1 arg2
```

**Comment by jhadvig** [comment]
:+1: I like the idea.. makes more sense to have the single input that would cover the cmd + args, and if anything user can switch to multiline editor. The question is if we shall make this the default behavior/layout of the `edit-command` directive or create another directive(if it makes sense to display cmd+args the way we are doing it presently on other pages).

**Comment by djdevin** [comment]
Just as an example, our typical production post-deploy step looks like this:

`drush -y rr --fire-bazooka && drush -y updb && drush -y fra && drush -y fr modulename --force`

While it's only 4 commands you'd have to enter it into 18 text fields I think - pretty complicated and prone to error.

As mentioned it would be nice if the multi-line input mimicked the behavior of Jenkins's "Execute shell" deploy step.

We could throw that into one command I suppose, but we would have to either pull it from a private repository or bundle it in the deployable image, so that would mean changing the post deployment step requires updating the source image.

Of course if there's a better way to encapsulate this let me know.

**Comment by spadgett** [comment]
@djdevin Would this work better? The link would change to the existing command editor.

@jwforres Opinion?

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/22834812/82e179ac-ef84-11e6-8df5-078703cee08d.png)

**Comment by djdevin** [comment]
For us, yes, absolutely. I may be biased because I'm used to Jenkins and other build systems but that is much clearer to me compared to the argument builder.

I think ideally, it would just be a resizeable textarea to allow for applications that have a lot of post-deployment commands. The resulting script can be executed with `sh -xe` so it would still trigger a failure if any one of the command lines failed.
