### ISSUE TITLE
Remove ::placeholder vendor prefixes once updated in PatternFly

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin-web-console#1261]
These rules included in https://github.com/openshift/origin-web-console/pull/1260 are added temporarily while awaiting an update to patternfly to fix https://github.com/patternfly/patternfly/issues/597

**Comment by spadgett** [comment]
@jwforres @rhamilto @jeff-phillips-18 FYI since we're about update Patternfly.

I think we have a fix for the wizard steps too that we can remove.

**Comment by dtaylor113** [comment]
@jwforres @rhamilto @jeff-phillips-18
> ...FYI since we're about to update Patternfly.
> 
> I think we have a fix for the wizard steps too that we can remove.
Is this the PR which addressed the 'wizard steps' issue:
https://github.com/openshift/origin-web-catalog/pull/223
If so, it looks like @priley86 PR is still open:  https://github.com/patternfly/patternfly/pull/645
Was the wizard issue fixed by https://github.com/patternfly/patternfly/pull/614 ?
- Thanks

**Comment by spadgett** [comment]
@dtaylor113 It's this style

https://github.com/openshift/origin-web-console/blob/1268da031a08bd67c377cb25bbd315339007f15c/app/styles/_patternfly-additions.less#L13-L16

I'm not sure if we have the same change in the catalog repo or not

**Comment by jwforres** [comment]
https://github.com/patternfly/patternfly/pull/614 was the one we duplicated
the fix on temporarily, but
https://github.com/patternfly/patternfly/pull/645 looks like something we
will want to pick up since we support IE11
