### ISSUE TITLE
Support selectors in DataService.watchObject

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#135]
Per this comment https://github.com/openshift/origin-web-console/pull/133/files#r69573887

@jwforres

**Comment by benjaminapetersen** [comment]
Quick skim of code, it *might* already work, the unique key in `.watchObject` is using the filters when generated:
```
var key = this._uniqueKey(resource, name, context, _.get(opts, 'http.params'));
```
I'll dig into this a bit more when I get the chance.

**Comment by benjaminapetersen** [comment]
@jwforres just checking in to see if this is something you might have fixed in what we talked about this morning.

**Comment by jwforres** [comment]
nope, didnt change this

**Comment by jwforres** [comment]
Because of the watch limitations in IE we probably need to wait to do this until we have multi-watch on a single connection.  Today there are places where we watch both an individual item in a resource and all of the resources for that type, but its only one watch connection. Switching to use selectors would make this two watch connections.

**Comment by benjaminapetersen** [comment]
Definitely looking forward to that!
