### ISSUE TITLE
Make View Event Details more prominent

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#1375]
So I kind of forgot this was here:

![screen shot 2017-03-22 at 11 59 31 am](https://cloud.githubusercontent.com/assets/280512/24207398/1d469860-0ef7-11e7-9b10-c50d3bece5e5.png)

But the "details" view from that tiny "details" link is super helpful.  Would be nice to make it more prominent.  Opening for discussion anyway.

@jwforres @spadgett @rhamilto @sg00dwin

**Comment by jwforres** [comment]
@ncameronbritt for UX opinion

**Comment by rhamilto** [comment]
I wonder if each event in the events sidebar should have a "View details" or "View more" link associated with it that links to the corresponding item on browse/events (e.g., browse/events/#eventID)?  When I'm browsing the events in the sidebar, I want to be able to drill down to the event I'm interested in so I can see all of its details.

**Comment by ncameronbritt** [comment]
I'm not 100% sure where this is in the UI... Do the info icons give you the more detailed information about the individual events?

**Comment by jwforres** [comment]
@ncameronbritt on the Monitoring page, and no the info icon is the event severity, its either Info or Warning

**Comment by ncameronbritt** [comment]
What about showing the entire message as a tooltip on hover, and making the list items clickable?

**Comment by benjaminapetersen** [comment]
That may be a lot for a tooltip, but maybe?  Its worth exploring, tho I def still think the ideal solution is to make the link to the dedicated events page more prominent.

**Comment by sg00dwin** [comment]
Since events are accessed within monitoring section, then you could argue the monitoring tab should have a secondary menu with an events link. That presents some challenges... 

The first being it would be a 1 link menu and wouldn't be as tall as the primary tab itself and looks weird. [***1**]  An option to fix that would be to include links to the pre-filtered monitory categories[***2**] - Pods, Builds, Deployments, Stateful Sets, but then the issue would be the bottom of the menu would be around the 725px viewport height and possibly be clipped on very small laptop screens. But could be lessened if Monitoring where moved above Storage.  


**1.** 
![screen shot 2017-04-19 at 1 34 41 pm](https://cloud.githubusercontent.com/assets/1874151/25193918/ad52a5aa-2506-11e7-9c5e-c249b449401e.png)


**2.**
![screen shot 2017-04-19 at 1 40 08 pm](https://cloud.githubusercontent.com/assets/1874151/25193917/ad51ebba-2506-11e7-9b73-2295a9d4f13a.png)

**Comment by benjaminapetersen** [comment]
Completely agree, 1 link submenu is 'bleh'.  Thinking about the 2nd option.

**Comment by ncameronbritt** [comment]
Maybe there options are Resources and Events?

**Comment by sg00dwin** [comment]
​I like that better.​

**Comment by rhamilto** [comment]
Now that the notification drawer is in place, is this still relevant?

**Comment by benjaminapetersen** [comment]
Nope!
