### ISSUE TITLE
new-app with docker strategy from web console

### ISSUE THREAD

**Issue by alikhajeh1** [openshift/origin-web-console#1399]
It feels like there's an obvious option missing from the Add to Project page... Users can use S2I or deploy an image, but not the `oc new-app --strategy=docker...` feature - which I've found very useful as it creates the imagestream/buildconfig/deploymentconfig/service. I imagine this is the main way users with existing Dockerfiles deploy their apps, so builds are done in OC (we normally configure GitHub webhooks to trigger builds).

It would be good if the web console supported this by having exactly the same UI as the Browse Catalog > Languages pages do, but instead let users specify the repo git URL where the Dockerfile lives (rather than use S2I), upload SSH key (or select existing secret) and specify any env/labels, routes etc.

**Comment by spadgett** [comment]
Related Trello card: https://trello.com/c/6CuBSnFF

**Comment by jwforres** [comment]
closing since this is being tracked in Trello already

**Comment by beezerbt** [comment]
@alikhajeh1 any chance you can share the oc CLI command you mention `oc new-app --strategy=docker... _feature - which I've found very useful as it creates the imagestream/buildconfig/deploymentconfig/service._ I am struggling to do exactly that on openshift online since at the Cluster level _even_ though there is an option for it, to Try it out, it actually does not allow it:
![image](https://user-images.githubusercontent.com/9202512/56656637-4af1d100-6696-11e9-919c-ad6b933b1eb7.png)

**Comment by spadgett** [comment]
Hi @beezerbt, this build strategy is not supported for OpenShift Online as discussed in #3124. You won't be able to add Docker strategy builds in the UI or through the CLI.
