### ISSUE TITLE
Clear filter link, in middle of page, doesn't remove remove filters when filtered by label

### ISSUE THREAD

**Issue by sg00dwin** [openshift/origin-web-console#1413]
<img width="696" alt="screen shot 2017-04-11 at 10 36 11 am" src="https://cloud.githubusercontent.com/assets/1874151/24915033/0b6a18c6-1ea4-11e7-8224-bf88b8d366e3.png">

**Comment by spadgett** [comment]
We're calling `LabelFilter.getLabelSelector().clearConjuncts()` to clear the filter, which I thought worked, but apparently not. We could remove the link when using the label filter, but I'd rather add a real API to `LabelFilter` for clearing it that we can use.

https://github.com/openshift/origin-web-console/blob/master/app/scripts/controllers/newOverview.js#L1056

Making this a P2 since the action simply doesn't work. It's something we should fix.

cc @jwforres

**Comment by jwforres** [comment]
two options right now, you can either call LabelFilter._clearActiveFilters()  which was originally a "private" method, but im not sure there is a reason for it to be.   Or, you can call LabelFilter.setLabelSelector(new LabelSelector());  which resets the label selector to have no filters set.

You should never directly modify the label selector of the label filter, the on change events of LabelFilter wont be fired.

**Comment by spadgett** [comment]
@jwforres `_clearActiveFilters()` clears the filter, but doesn't remove the active filter UI elements I could use `new LabelSelector()`, but I feel like the widget should have a public `clear()` method.
