### ISSUE TITLE
Not obvious that the app label can be changed

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#1422]
The app label in the UI is not modifiable and this is a bug (it should be) as it is from the CLI.

![image](https://cloud.githubusercontent.com/assets/78350/25083382/0f68f714-2357-11e7-9f5a-9e829f1415c6.png)

As explained by @bparees in an email:

> here's the label applying logic for new-app:
> 
> for non-template deployments:
> 
> 1) if the user provides labels on the command line, assign those labels
> 2) assign the default app=name to all objects, unless (1) already set the "app" label.
> 
> for template deployments:
> 
> 1) if the template defines labels, assign them
> 2) if the user provides labels on the command line, assign those labels (possibly overwriting values from (1)
> 3) assign the default app=name to all objects unless (1) or (2) already set the "app" label or any of the objects otherwise already has an app label defined (in which case we don't set it on any object).
> 
> So there should always be *an* app label available unless your template explicitly defines the app label on only a subset of objects in the template.

**Comment by spadgett** [comment]
@jorgemoralespou You can change it, but you have to type it again on a new line to override. This isn't obvious. The web console behavior for templates should be the same as the CLI.

@jwforres I think it might be better to simple prefill the value and let users modify it instead of retyping it. If we don't want users to remove the app label, we could always make the name readonly and remove the `x`.

**Comment by jorgemoralespou** [comment]
@spadgett @jwforres I agree with the proposal to make name read only.

I consider myself an advanced user and wasn't obvious at all. Would never have expected to have 2 create a new label to override the name.
