### ISSUE TITLE
Tooltip clipped behind list row header at mobile

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1454]
![screen shot 2017-04-20 at 8 38 42 am](https://cloud.githubusercontent.com/assets/1167259/25231168/d51445f0-25a4-11e7-80f6-9b741c69ff6b.png)

**Comment by spadgett** [comment]
It also gets clipped behind the alert.

![screen shot 2017-04-20 at 8 44 45 am](https://cloud.githubusercontent.com/assets/1167259/25231370/a9a6a100-25a5-11e7-82e3-0cc2679d2e43.png)

**Comment by spadgett** [comment]
I understand that the tooltips don't currently appear for the donut at mobile, but I'd like to check that they aren't clipped for metrics before closing. (I don't currently have metrics enabled to try.)

In the previous overview, we had a conditional class that only set the overflow styles when a deployment was in progress:

https://github.com/openshift/origin-web-console/blob/master/app/views/overview/_dc.html#L1

**Comment by rhamilto** [comment]
Metrics tooltips are getting clipped, too.  

![screen shot 2017-04-20 at 9 29 32 am](https://cloud.githubusercontent.com/assets/895728/25233174/ee7e8e04-25ab-11e7-8687-1251734beec1.PNG)

@sg00dwin, @spadgett suggests we add a class to control overflow so that it's only applied when a deployment is in progress.
