### ISSUE TITLE
Overview task list failed message easy to miss, has bad margins

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#154]
The failed message margins are wrong (no bottom margin). I think it needs to be called out more too with a big red 'x', etc.

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/16770141/8c56fb78-4819-11e6-937d-46e8e1e26ef4.png)

@jwforres @sg00dwin @rhamilto

**Comment by jhadvig** [comment]
@spadgett are we still talking only about the bottom margin ? Or we want to make the Task more visible ?

**Comment by spadgett** [comment]
Both. The margins look off, but it's not obvious enough that an error occurred. I think we can improve the styling.

**Comment by jhadvig** [comment]
@spadgett so I've played a bit with the styling and came up with two drafts for Tasks with and without errors:

## With Errors ##
1#
![screenshot-34](https://cloud.githubusercontent.com/assets/1668218/17054088/87e3456c-5005-11e6-8daf-f30e1915f89a.png)
![screenshot-35](https://cloud.githubusercontent.com/assets/1668218/17054089/890922ae-5005-11e6-8017-175bbd750c1d.png)

2#
![screenshot-36](https://cloud.githubusercontent.com/assets/1668218/17054096/90db2b62-5005-11e6-956c-5e1ccbf8ecbc.png)
![screenshot-37](https://cloud.githubusercontent.com/assets/1668218/17054104/9562942c-5005-11e6-9c02-1f7db1165d56.png)

Got rid of the X button, since from the user perspective it would be better to have it next to the "Show details button" so after revealing the details user can almost immediately dismiss the Failed Tasks.

## Without errors ##
1#
![screenshot-41](https://cloud.githubusercontent.com/assets/1668218/17056491/dfbb5e60-5013-11e6-815f-65fc43be1c74.png)
2#
![screenshot-42](https://cloud.githubusercontent.com/assets/1668218/17056497/e40fdd38-5013-11e6-8f06-d090effb9266.png)

Here I'm using just a small icon or no icon at all since there is no need to highlight the Tasks section even more since there were no errors.

The idea was to combine the styling of the resources we show on the overview page && alerts.

cc'ing @rhamilto && @sg00dwin for additional feedback

**Comment by spadgett** [comment]
I like the big warning icon, but I'd make an error icon (red `X`) if there are any failures. I'd probably also go with just a white background. The success and errors alerts on top of the yellow background look weird.

For success, maybe a big green check and details hidden by default.

This is definitely an improvement.

**Comment by jhadvig** [comment]
@spadgett like this ? 
## error ##
![screenshot-50](https://cloud.githubusercontent.com/assets/1668218/17058401/91a03acc-5020-11e6-8450-baf6f44e5615.png)
![screenshot-51](https://cloud.githubusercontent.com/assets/1668218/17058403/92db80ae-5020-11e6-9b49-30b25fe578e6.png)

## success ##
![screenshot-44](https://cloud.githubusercontent.com/assets/1668218/17058430/b336b698-5020-11e6-816f-594eb663a2b4.png)

**Comment by spadgett** [comment]
@jhadvig that looks really good. maybe a bit more right margin after the icon.
