### ISSUE TITLE
Failed build page gives too little space for the log

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin-web-console#1695]
All of the room taken up on the left half by the build name seems like it could be used to show more build log output.

![screenshot from 2017-06-13 09-24-47](https://user-images.githubusercontent.com/7328370/27093056-35ea385e-501a-11e7-83c2-7410fcea8bb5.png)

**Comment by spadgett** [comment]
On the fence about changing this since we have a number of items that all align in the right column. There can be multiple builds with logs as well, which will take up more vertical space if we stack builds, and often the logs are hidden.

![openshift web console 2017-07-25 17-39-58](https://user-images.githubusercontent.com/1167259/28595114-6e072370-7160-11e7-94ae-cb6e0ca5ef01.png)

**Comment by spadgett** [comment]
We could look at changing this to use the new log snippet and change layout for failed builds.
