### ISSUE TITLE
Label filters in table toolbar should be wider like other label filters

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1824]
These look like they're different types of filters, although they're really the same. I think part of it is that the widths are so different. We should have the table filter expand the to the same width.

![openshift web console 2017-07-11 12-23-56](https://user-images.githubusercontent.com/1167259/28078738-d4d25c92-6633-11e7-9815-a53066722d87.png)

![openshift web console 2017-07-11 12-22-55](https://user-images.githubusercontent.com/1167259/28078708-c5c16680-6633-11e7-8548-336bf5258cb0.png)

@ncameronbritt

**Comment by ncameronbritt** [comment]
There's the width question, but there's also the question of whether the the filter should be part of the table. PF docs have both. 
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/table-view-navbar.html
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/table-view.html

In the cases you're showing, it makes sense to me to have the filter as part of the table, since that's all the the filter is acting on. @openshift/team-ux-review what thoughts do you have?

**Comment by spadgett** [comment]
> In the cases you're showing, it makes sense to me to have the filter as part of the table, since that's all the the filter is acting on

+1, it would also be really odd to go to the events tab and see two filter controls, with only one of them working on the events

**Comment by spadgett** [comment]
Related PR for events table filter styles: #1826
