### ISSUE TITLE
Inconsistent layout on storage and routes pages

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1916]
Persistent Volume Claims is the only table on the Storage page, so I'm not sure it really needs the secondary header. We're inconsistent in when and how we use "Storage" vs "Persistent Volume Claim."

The Create button is in a different position as well. Since there's only one table both pages I suggest we position it in the same place on both.

@jeff-phillips-18 since you're add the `fa fa-plus` icon to the project list button, I wonder if we shouldn't add it to the similar buttons on these pages and maybe give it the same primary button style.

@openshift/team-ux-review 

Storage page:

![openshift web console 2017-08-07 17-02-29](https://user-images.githubusercontent.com/1167259/29045644-3bc61074-7b92-11e7-9887-c749ca59018a.png)

Routes page:

![openshift web console 2017-08-07 17-03-00](https://user-images.githubusercontent.com/1167259/29045654-4951b11c-7b92-11e7-8965-ab539f930dbb.png)

**Comment by spadgett** [comment]
We frequently refer to it as "Storage" or "Persistent Volume Claim" inconsistently in other contexts.

![openshift web console 2017-08-08 08-45-04](https://user-images.githubusercontent.com/1167259/29072511-ff2c63dc-7c15-11e7-9487-9abbb9714af8.png)

Breadcrumbs:

![openshift web console 2017-08-08 09-06-12](https://user-images.githubusercontent.com/1167259/29073230-dfe47cf0-7c18-11e7-9db6-d251cd6b9a88.png)

**Comment by ncameronbritt** [comment]
I think one potential short term fix to make these particular pages more consistent would be to add "Persistent Volume Claim" to the table, maybe instead of name, and position the button as it is on the other page.

But as @spadgett points out, there is a larger issue here around "storage" vs "persistent volume claim" and how/if we expose the underlying Kubernetes concepts in the UI. Perhaps the UI could be more helpful in educating novice users who may not be familiar with the Kube concepts.
