### ISSUE TITLE
Application route scoring picks the wrong route

### ISSUE THREAD

**Issue by siamaksade** [openshift/origin-web-console#1926]
The application route scoring algorithm is too enforcing and makes wrong assumptions about how an application would look like:
https://github.com/openshift/origin-web-console/blob/master/app/scripts/services/routes.js#L106

The following is a simple microservices application which consists of three pods each with their own routes. A is the web pod, B and C provide REST APIs:
```
       +---+
       | A |
       +---+
         |
    +---------+
    |         |
  +-v-+     +-v-+
  | C |     | B |
  +---+     +---+
```

The new UI picks one of the routes randomly since all three score the same while from the user's perspective, route A is considered the application route and the entry point to this app.

**Comment by spadgett** [comment]
@siamaksade Do you have suggestion for how to improve the scoring, or would you rather be able to pick the route for the app?

**Comment by siamaksade** [comment]
It's not possible to create a scoring that matches the majority of cases
since applications look widely different from team to team.

I'd suggest allowing users to label or annotate the main route to hint
which one to pick. For example the it could first look for a route with
label app-route=true and if not available then score the routes and pick
one.

**Comment by spadgett** [comment]
It's really meant to be a best effort and not anything definitive. We only have space to show a single route in this view, so rather than picking a random one, we try to use a route with a custom hostname rather than a generated route.

I'm a little hesitant to introduce a label or annotation just for display because that caused confusion in the past. I'm thinking specifically of service grouping. Many users weren't sure if it changed behavior when it was only used for how we displayed deployments on the overview.

I'm wondering if the real problem is that we need a different view like a topology view or more of a microservices-focused view. We have a card for alternative views.

https://trello.com/c/qklWJUHC

**Comment by siamaksade** [comment]
This is not really to introduce anything new but rather to fix the new "application" concept introduced in 3.6 based on grouping of the deployment configs with the same "app" label. 

User can choose to group resources into the new "application" concept but they have zero control on the route that is visible in the console as the application url:

Take this example:
<img width="918" alt="openshift-app" src="https://user-images.githubusercontent.com/1174934/29367556-7726741a-82c7-11e7-9aed-9a71e1597e01.png">

The above is completely misleading because http://catalog-coolstore.host is not the URL to reach this "application" and the user has no way to change that behavior. It's fine that scoring is a best effort mechanism but not ok that it is forced upon the user.

**Comment by spadgett** [comment]
I understand the problem, and I'm not arguing there's not an issue. We'll have to think about how to fix.

The proposed solution using labels or annotations also has drawbacks. From experience, I'm hesitant to go ahead with that because we've received negative feedback for similar approaches in the past.

@openshift/team-ux-review

**Comment by siamaksade** [comment]
I understand. I meant label and annotations as one solution but any solution that would give the control back to the user would be fine :)

**Comment by jorgemoralespou** [comment]
@spadgett even if there is an alternate view, I agree with @siamaksade that in this view there needs to be a way to select which route to display. 
I would think that making it something that the UI would solve visually in the route selection, and making that an annotation is the best way to move forward. Annotations are meant for these type of things, and even though the service relation was confusing it was not because of the annotation but rather to the fact that it didn't do anything other than visualize services grouped, which is not what you would expect. In this case, I would think that if you have a checkbox marking a route as primary, that would not confuse anybody. Maybe being more explicit in the annotation name and UI feature.

The problem would then be the logic, as to what to do when one selects a route as default, but there's already another route as default? Worth considering, but in any case, it will most likely still be required to annotate the "objects" for an alternate view to know how to properly display.

**Comment by spadgett** [comment]
> In this case, I would think that if you have a checkbox marking a route as primary, that would not confuse anybody.

I'm not sure. That sounds to me like the platform will do something special with the "primary" route. I'm not saying we can't use an annotation, just pointing out that we should be careful to explain that it's only for the UI.

**Comment by siamaksade** [comment]
The the "application" concept (set of deployment configs with identical "app" labels) has any effect in the platform other than in the UI?

**Comment by openshift-docker** [comment]
Special, one-off annotations that only a select group of people know about
isn't going to improve most user's lives (i.e. it makes some of your demos
better, but not substantially).  I'd argue we should be looking for
representations that makes it easier to realize there are multiple routes,
or trying to come up with actual meaningful labels we can put behavior
around (in both the UI and CLI and router) to help admins prioritize.  If
we had router metrics, i'd weight the route with the most traffic.  If
you're deploying frequently, I'd weight the route that shows the most
frequently updated deployment.

**Comment by siamaksade** [comment]
@openshift-docker That's a good point. If we take a step back, the use-case description would be that as a user, I need to compose an application based on the resources deployed. Regardless of if done via Console or CLI, composing an application consist of choosing the objects that form the application and picking the primary route, if any, for that application. 

The confusion and annotation discussion right now is due to the fact that visualization of application is already implemented in the UI without implementing the above use-case.

**Comment by spadgett** [comment]
I'm wondering if we should just show all the routes or perhaps a summary if there are multiple. Maybe say "3 Routes" with a popup or click to expand link showing all the routes?

@openshift/team-ux-review

**Comment by ncameronbritt** [comment]
Seems clear that we need to make all of the routes available somehow in this view since we can't be sure we'll correctly guess the primary route. Listing them all seems risky because it could potentially take up a lot of space if there were more than a couple, and you might not care about all of them. Maybe some expand/collapse behavior, e.g. "Show 2 other routes"?

**Comment by siamaksade** [comment]
IMHO "expand/collapse" make sense. It allows seeing the other routes and doesn't take more space at the same time.

However it doesn't solve the original problem: we have given users a way to group objects into an "application" and but we don't give them a way to pick the main route. We "force" them to take our guess.

If we let users use annotations to group objects, I don't see why we shouldn't use annotations to allow them choose the main route. This of course can be also in UI when editing the routes as a checkbox titled "primary application route" or something similar.  

As an alternative we can take the "application" grouping away so that each service can appear separately with its own route.

**Comment by spadgett** [comment]
> If we let users use annotations to group objects, I don't see why we shouldn't use annotations to allow them choose the main route. 

We no longer use annotations for grouping.

> As an alternative we can take the "application" grouping away so that each service can appear separately with its own route.

"List by Resource" on the overview does this, so it's possible today.

**Comment by spadgett** [comment]
> "List by Resource" on the overview does this, so it's possible today.

Although it doesn't show the route until expanded, so I guess it's not the same. But we'll have the same problem there if a deployment has multiple routes.

**Comment by siamaksade** [comment]
> We no longer use annotations for grouping.

How do you mean? "List by Application" still exists in origin 3.7-alpha1 and has the same behaviour. It uses "app" label to group the deployment configs and guesses the main route.

**Comment by siamaksade** [comment]
AFAIK app=appName label is only meaningful to the web console. Everywhere
else it's just a label like any other label, no?

**Comment by spadgett** [comment]
> AFAIK app=appName label is only meaningful to the web console. Everywhere else it's just a label like any other label, no?

Which you can use in a label selector and on the CLI with `-l`. And it gets set by `oc new-app`.

My point is the label is not there for overview grouping (unlike the old annotation we had). It's there for other reasons, and the web console uses it because it's already set and makes sense.

**Comment by jorgemoralespou** [comment]
@spadgett @openshift-docker I would agree with you if there was an easy way to solve this, but since I don't find an easier way than annotating the route, I would "at least" consider what it would imply.

This is how we manage source secrets (https://docs.openshift.com/container-platform/3.5/dev_guide/builds/build_inputs.html#automatic-addition-of-a-source-secret-to-a-build-configuration) and it's still in many other places. I'm not saying the developer should know how to annotate this object, I would encapsulate that in the "oc expose, oc create route commands as well as in the UI, ..."

And to your point @spadgett, can I change the overview to group things by other label, e.g: microservice, instead of app? If not, app is a key concept in the UI. Then, even if the app is there an you just use it, it's really only meaningful to the console (as of now).

**Comment by elmiko** [comment]
hi, just found this issue but it is a pain point we are experiencing as well. we have an application with multiple pods grouped together and 2 of them have routes exposed, but we would like to have our users only use 1 of these routes.

we are currently trying to do some hackery to get it to display our preferred route, but this is non-ideal. i don't quite follow the problems with letting the user select an annotation for the primary route, but some way to specify this would be greatly appreciated.

**Comment by liggitt** [comment]
hit this today with an app that includes two routes, one of which is for API use and one which is for UI use. The incorrect one was displayed.

At minimum, I'd expect an indication there are other routes and way to access the other routes (link, in-place expansion, etc)

Nice to have would be a way to indicate UI-oriented routes, or primary routes that would influence the selection by the console

**Comment by liggitt** [comment]
If you expand the deployment, both routes appear in the "networking" section next to their respective service... I just didn't realize there were multiple routes, and the URL hoisted out of the collapsed section kept me from digging.

Possible solutions when there's more than one service:
* change the hoisted text to the service names, linked to the URL (so instead of https://foo.bar.baz you see [service1](https://service1) | [service2](https://service2))
* change the hoisted text to a "Multiple routes" link that expands and navigates to the networking section

**Comment by spadgett** [comment]
Raising priority since this is clearly problem with the user experience.

**Comment by jorgemoralespou** [comment]
@spadgett any update on what's being thought of for this?
We're constantly hitting this with applications that have multiple components that are exposed. For now, we're removing all those routers from the application, as else, an incorrect route link in the web UI does not help, and you need to either expand the deployment or go through the routes page.

**Comment by siamaksade** [comment]
Everyone agrees on the issues here but all suggestions so far are rejected in favour of a better solution that has not presented itself yet :) 

Here is the summary of suggestions:
1) Allow users to pick the main route (via UI, annotation, label, etc)
2) Show all routes 
3) Change the UI completely and display for example the topology instead

If it was to vote, I'd vote for (1) as the least obstructive solution.

**Comment by serenamarie125** [comment]
We will look into a design solution for this.  Adding a story to our backlog, and will report back with a suggested solution. @jorgemoralespou @spadgett

**Comment by ncameronbritt** [comment]
One of the design options we are considering is something like the following: There's an action near the route that allows the user to choose a different route. This would bring up a modal or popover for the user to navigate to a different route and/or change which route is displayed in the Overview. 
![screen shot 2017-11-14 at 11 54 25 am](https://user-images.githubusercontent.com/8974593/32793077-f09391be-c932-11e7-819a-cfc2b43d1e16.png)
![screen shot 2017-11-14 at 11 54 40 am](https://user-images.githubusercontent.com/8974593/32793085-f62b5bc0-c932-11e7-8b9c-e711179d4719.png)

Would you imagine changing what route is displayed would be per user/per browser? Or would you imagine that such a change would affect all users? If the latter, it may be the case that different users would be interested in different routes, depending on their roles. It may also be the case that some users would not be able to edit/change what route is displayed if they don't have permission to edit routes.

**Comment by crobby** [comment]
For the scenario that has me running into this problem (same as @elmiko), we would want this change to affect all users, but I can envision a world where someone may want different functionality.

**Comment by siamaksade** [comment]
It would affect all users. The choices of route is about the application
topology IMHO which is defined per applicants rather than per user.

Would there be a way to choose the route via CLI or via templates as well?
That would be needed when there is a pipeline involved and objects
constantly get recreated.

**Comment by spadgett** [comment]
> Would there be a way to choose the route via CLI or via templates as well? That would be needed when there is a pipeline involved and objects constantly get recreated.

We'd probably implement it as an annotation on the route that you could add to the template.

**Comment by jorgemoralespou** [comment]
I like the design. Just an additional request.

In some of the applications I have developed I have a main entrypoint, which is the one I want most visible, and I want this to be always the same, even if I add more components, so I would expect to have an annotation to the route to mark it as primary, and also an easy way when I create a route (at least in the UI) to mark that route as primary. This seems to be accomplished. If my application (grouping) only has one deployment/route, I would not expect to mark that as primary, although it should still keep working.

I would also like, as I might have routes for many of the deployments, to have a link at the collapsed view for every deployment, so I can still go to the individual routes, which are not the primary.

The only concern I have is how things would behave if there's multiple routes with the annotation that mark it as primary. But this is a minor nitpick.

**Comment by elmiko** [comment]
@ncameronbritt i like the proposed solution as a base point for starting this work, i also like what @jorgemoralespou is saying about the possibility of showing all the routes.

thanks for the attention on this issue!

**Comment by jwforres** [comment]
Since discussion on this seems to have settled and we've gotten an RFE in for this I would like to move this into Trello now https://trello.com/c/CFNncxCB

**Comment by rhamilto** [comment]
The ideal solution to only show the preferred route(s) requires the addition of an annotation to the route(s).  Given this annotation will only be used for this one specific use case (the display of the route on the overview page of the web console), @spadgett has significant reservations about adding said annotation.  An alternate solution is to simply show more than one route on the overview (up to a maximum number to be determined with an optional link to show all routes).  Would this alternate solution sufficiently address the primary concerns (and thusly remove the need for the additional annotation)?

![ay2c14a](https://user-images.githubusercontent.com/895728/37096430-8eacc6a2-21e6-11e8-978b-b242b493bbde.png)

**Comment by ncameronbritt** [comment]
After talking with @spadgett more about this, it seems like it will be necessary to add an annotation to make this work. 

Since having an annotation at all seems like a prerequisite to doing anything else, what if we take the first step of allowing template authors, etc to add an annotation to routes that would boost them to the top of the scoring algorithm? Then if necessary, we can circle back on the question of whether/how to add this annotation through the UI. 

IMO, the questions about how to indicate that there are multiple routes associated with an application, or how to show that a deployment is exposed externally are related, but separate from this issue.

**Comment by jorgemoralespou** [comment]
@ncameronbritt in that case, would you open those issues and link here?

**Comment by ncameronbritt** [comment]
@jorgemoralespou Here is an issue for indicating that there are multiple routes associated with an application https://github.com/openshift/origin-web-console/issues/2884

@spadgett Mentioned that we may want to have a card for showing in the collapsed state that a deployment is exposed externally.
