### ISSUE TITLE
Safari keeps asking for a client certificate

### ISSUE THREAD

**Issue by mliker** [openshift/origin-web-console#1953]
Hi,
how can one avoid being asked for a client certificate by the openshift web console in Safari?
This happens every minute or so.

openshift origin 1.5 (actually since 1.3, my first os installation)
Safari 10.1.2
MacOS 10.12.6 (Sierra)

<img width="1280" alt="screen shot 2017-08-21 at 13 26 14-editted" src="https://user-images.githubusercontent.com/1681893/29517495-b5d9766a-8675-11e7-8332-af8c6100af5b.png">

**Comment by spadgett** [comment]
Unfortunately, this is a Safari bug. Safari is incorrectly prompting for a certificate even when none match the CA required by the server. The client certificate is optional, even though Safari says it's required.

https://bugzilla.redhat.com/show_bug.cgi?id=1259029#c5

Closing this issue since it's tracked by the linked Bugzilla.

cc @liggitt

**Comment by mliker** [comment]
Thanks for the bugzilla link. I opened a bug with Apple
