### ISSUE TITLE
Port icon doesn't display on container details

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#2066]
![screen shot 2017-09-13 at 11 37 52 am](https://user-images.githubusercontent.com/8974593/30386560-187f2a12-9878-11e7-981e-589db73afc3d.png)

**Comment by rhamilto** [comment]
Good catch, @ncameronbritt!  With @sg00dwin's help, I was able to track down what should be there.  It's this:

![screen shot 2017-09-13 at 2 23 01 pm](https://user-images.githubusercontent.com/895728/30393771-274270e2-988f-11e7-898d-430898bb9fff.PNG)

The bug exists because the icon font that defines that character is no longer included in the console.  I overlooked this one case [when the font was removed](https://github.com/openshift/origin-web-console/commit/79909e7599a80ffc80bf62e0cd57507f8c54adf0#diff-b90547ad519fad2d6cf44b74b4b089ff) because it's being included using [data-icon] instead of our standard [class].  My bad!

That said, I don't think we want to add back the font for this one icon.  So, what should we use instead?  There's http://fontawesome.io/icon/heartbeat/ in Font Awesome, but it adds the heart, and I'm frankly not sure I understand what an ekg heartbeat has do do with ports anyhow.

Given that PatternFly's icons for service
![screen shot 2017-09-13 at 2 41 22 pm](https://user-images.githubusercontent.com/895728/30394654-b2add6a6-9891-11e7-917b-52efbdbeaca1.PNG)
and route
![screen shot 2017-09-13 at 2 41 28 pm](https://user-images.githubusercontent.com/895728/30394675-c5c9cbe6-9891-11e7-8651-45fbd7d34f85.PNG)
incorporate an arrow pointing right, and we use similar arrows to denote the relationship between ports,
![screen shot 2017-09-13 at 2 40 41 pm](https://user-images.githubusercontent.com/895728/30394769-1d3bbaba-9892-11e7-9457-90fc98983db7.PNG)
![screen shot 2017-09-13 at 2 40 53 pm](https://user-images.githubusercontent.com/895728/30394770-1d5f4bb0-9892-11e7-865a-8e1bbc0e716c.PNG)
what if we use a single arrow pointing right for the port icon?
![screen shot 2017-09-13 at 2 48 17 pm](https://user-images.githubusercontent.com/895728/30394973-ba333dfc-9892-11e7-811c-d6e77f82436f.PNG)

thoughts @spadgett, @sg00dwin, @benjaminapetersen, @openshift/team-ux-review?

**Comment by benjaminapetersen** [comment]
The change works for me.  The 2 `pf-icon` options are a touch on the noisy side, the plain arrow is clean & simple.

**Comment by ncameronbritt** [comment]
It was Jenny that caught it. Credit where it's due. 👍 

She probably has thoughts about the icon.

**Comment by spadgett** [comment]
> She probably has thoughts about the icon.

She suggested `fa-flash`

**Comment by spadgett** [comment]
Although we've used that in the past for "instant app," so I wonder if it will be confusing.

**Comment by spadgett** [comment]
cc @jennyhaines

**Comment by jennyhaines** [comment]
@spadgett @ncameronbritt - Is "instant app" currently an idea in OpenShift? If no, I would encourage the use of fa-flash, stilll because it seems general enough of an icon to represent ports.  The arrow seems to be related to a process, and it says "look here" to me. When paired before text, it also could look like a bullet point alternative.

If the fa-flash is an absolute no, there is also "fa-dot-circle-o", which could signify a port/endpoint. 
![fa-dot-circle](https://user-images.githubusercontent.com/24898297/30397110-bd91b030-9899-11e7-8099-a611c72c95c7.png)

**Comment by spadgett** [comment]
@jennyhaines This is how we used to use that icon, although it's no longer used this way:

<img width="764" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/11984612/a5bcdda4-a98a-11e5-8a2a-7b344b835c5f.png">

**Comment by spadgett** [comment]
Does it make sense to look at adding a port icon to Patternfly? The icon we used to have worked really well (see Robb's comment above).

To me ports are about connecting things, so an icon that conveys that idea is ideal.

**Comment by jennyhaines** [comment]
@spadgett - Yes, I can look into adding that port icon back in. I don't ever remember any discussion on this end about removing it, so the removal must have been accidental.

**Comment by rhamilto** [comment]
> @spadgett - Yes, I can look into adding that port icon back in. I don't ever remember any discussion on this end about removing it, so the removal must have been accidental.

![screen shot 2017-09-13 at 2 23 01 pm](https://user-images.githubusercontent.com/895728/30393771-274270e2-988f-11e7-898d-430898bb9fff.PNG) was never part of PatternFly.  It was part of a now deprecated and removed OpenShift icon font.

**Comment by jennyhaines** [comment]
@spadgett @rhamilto @ncameronbritt - I recreated the ports icon (below) to look good for low and high pixel density screens, and can see about adding it into PatternFly. What do you think?
<img width="46" alt="ports" src="https://user-images.githubusercontent.com/24898297/30441300-07883aa8-9947-11e7-86cb-162a6b8256e4.png"> 
![ports-14px](https://user-images.githubusercontent.com/24898297/30441316-135ba996-9947-11e7-985e-0f6543448ecf.png)

**Comment by spadgett** [comment]
@jennyhaines To me it looks great!

**Comment by rhamilto** [comment]
WFM

**Comment by ncameronbritt** [comment]
Yep!

**Comment by rhamilto** [comment]
@jennyhaines, any update on this icon being added to PatternFly?

**Comment by jennyhaines** [comment]
Hi Robb- I'm trying to coordinate the PatternFly font update for mid next week. We actually have a bunch of other icons that should be making their way in at the same time! I will let you know as soon as the port icon is up!

**Comment by rhamilto** [comment]
@jennyhaines, any update on the new icons?  3.7 release is rapidly approaching, and we'd like to get this fixed before the release.  Thanks!

**Comment by jennyhaines** [comment]
Hi @rhamilto - I'm excited to say that the port icon (as well as others for OpenShift!) are being added today by Andres on our team. He is going to let me know once they are all in, and I'll let you know!

**Comment by jennyhaines** [comment]
@rhamilto - the port icon has been added to PatternFly! It's ready to use!
