### ISSUE TITLE
Marked for deletion "in a few seconds"

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2175]
This should say "just now" or "a few seconds ago." (I might have a client clock skew, but we should never show a future value.)

![screen shot 2017-09-26 at 4 28 32 pm](https://user-images.githubusercontent.com/1167259/30882696-d2ecf9f6-a2d7-11e7-9649-1a25e8eab6c3.png)

**Comment by jhadvig** [comment]
in favour for the "few seconds ago", since term "just now" is pretty relative in this terms

**Comment by jwforres** [comment]
So we already started normalizing all negative durations to 0 since we knew they were caused by clock skew.  I would be tempted to do the same with the relative timestamp helpers since nothing we work with today has future dates.

The exception will be CronJobs that are scheduled in the future.  We could do something like adding a flag to relative timestamp that allows future dates and you have to opt in to that.

**Comment by jwforres** [comment]
So actually we do not have a relative timestamp in any of the other deletion messages.  We should remove this timestamp entirely for consistency. That is the least risky fix at this point.
