### ISSUE TITLE
Should we show service icon on overview and provisioned service page?

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#2221]
We have an icon for provisioned services. Should we show it somewhere on the overview or the provisioned service page? @ncameronbritt is looking at icons for any deployment, but provisioned services have an out-of-the-box icon we could easily show.

Question came up in https://github.com/openshift/origin-web-catalog/pull/465#issuecomment-334452830

@jeff-phillips-18 @openshift/team-ux-review

**Comment by ncameronbritt** [comment]
Here how that might look monochrome icons:
![screen shot 2017-10-05 at 2 48 32 pm](https://user-images.githubusercontent.com/8974593/31246787-89d00a7c-a9dc-11e7-9fb6-0d5769bb0c68.png)

And with color icons:
![screen shot 2017-10-05 at 2 49 51 pm](https://user-images.githubusercontent.com/8974593/31246797-93a76bbc-a9dc-11e7-8830-35d190eda1fc.png)

The sense among the designers was that, if we eventually add icons to deployments, the monochrome version was preferable. Things got too busy with the color svgs.

**Comment by ncameronbritt** [comment]
(The screenshot isn't totally up to date -- the service names should be links.)

**Comment by serenamarie125** [comment]
@ncameronbritt I agree that the icon should be shown.  I'm curious as to why we wouldn't show it in full color.  Given the mocks shown here, I don't think it looks bad.  Since we are going through an effort of making things full color, i'm curious as to why we would go to monochrome here rather than take advantage of the new visual assets.

**Comment by ncameronbritt** [comment]
@serenamarie125 When I showed the work I had done on this to the other designers today, the consensus was that with the full-color icons for all of the deployments, the color made the page overly busy and disrupted the hierarchy of the page. They can chime in if I'm misrepresenting their opinions.
![screen shot 2017-10-05 at 3 50 18 pm](https://user-images.githubusercontent.com/8974593/31249366-0b56d3e8-a9e5-11e7-8ac5-bee49608eef1.png)


There may be more that can be done from a visual standpoint to mitigate the busy-ness of the page. The icons could be smaller, for example. But I'm not sure how much smaller they could be and still be intelligible. And the visual weight of icons will vary, so for example, Ruby will probably always stick out by virtue of its color.

**Comment by beanh66** [comment]
@ncameronbritt Yeah initially seeing the monochrome one and this one side by side, the monochrome icons seemed a lot cleaner alongside the rest of the overview "noise" such as warning/error icons, links, pod charts, etc. With that said, this image alone doesn't look bad to me so I don't have a strong preference! 

One thing I didn't really consider until just now was the recognizability factor. Since the icons are color on the catalog homepage (which I agree looks way better), we may want to be consistent here so users know what to look for after adding something to their project. This may be a reason to consider keeping the color but curious what everyone thinks.

**Comment by cshinn** [comment]
I don't have a huge problem with the color icons here, and I agree that if we're going to put icons on this page at all they should probably use the same representation everywhere we show them

**Comment by ncameronbritt** [comment]
Since the icons can be different shapes, i.e. not all squares, I experimented with a way to scale the icons so that taller, skinnier icons look more proportional to square ones, for example. I think that it's an improvement.
![screen shot 2017-10-09 at 10 10 25 am](https://user-images.githubusercontent.com/8974593/31342315-60f02712-acda-11e7-97d7-9c407b008afe.png)

**Comment by spadgett** [comment]
@ncameronbritt What do you recommend when we don't have an icon for everything?

Provisioned services should always have something, but I'm not sure if we always will for other deployments.

**Comment by ncameronbritt** [comment]
I don't know that I have any great ideas, but here are some ideas:
- pick a default icon if there isn't one
- allow the user to choose an icon
- design it such that the icons aren't so prominent, and are not missed if they're not there.

The case I'm worried about is if you had a few application groupings, and some deployments  have icons and some don't. It could look pretty disjoint.

Definitely interested in other ideas, if @openshift/team-ux-review  has any.

**Comment by rhamilto** [comment]
I dislike the addition of icons on the overview as they add noise to the page making it harder to parse what is important such as errors or build and deployment statuses.

**Comment by beanh66** [comment]
@rhamilto @ncameronbritt @spadgett Should we consider only showing icons for the provisioned services on the overview?

**Comment by rhamilto** [comment]
> @rhamilto @ncameronbritt @spadgett Should we consider only showing icons for the provisioned services on the overview?

The downside to that is it gives more prominence to provisioned services than the other items on the page.

**Comment by ncameronbritt** [comment]
The story I was tasked with was essentially to explore adding icons to the overview. I think I agree that they just make the page noisier. The use case for the icons that was mentioned to me involved allowing a user (presumably a user new to a project) to see at a glance what language deployments are using, or which are databases, etc. A user can't necessarily glean that information from the names alone. There may be other ways to go about it other than showing icons.

**Comment by jorgemoralespou** [comment]
I would probably agree with @rhamilto that the icon distracts from other informationin the collapsed view, but that's mostly because it's much bigger, or better said, the rest of the information is much smaller, which gives it less relevance.

If you look into this view:
https://raw.githubusercontent.com/kubernetes/dashboard/master/docs/dashboard-ui.png

All items in the line are same size, font, etc,.. and they use colors to see at first glance what should be relevant, status of the pod and metrics. I would think that we could compact information by using less text and more visual indicators, that would use less horizontal space, eventually providing more information in the collapsed view, while still occupying the same vertical space.
