### ISSUE TITLE
Retry tests when they fail

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#2280]
We can at least better detect flakes.  Another test framework update I want to tackle in the future.

**Comment by spadgett** [comment]
Maybe something like https://www.npmjs.com/package/protractor-flake ?

**Comment by benjaminapetersen** [comment]
Yup, looking at that one as well.  Just have to decide behavior.  If we run 2x, does it need to pass both times to be seen as a success, or does 1 fail (flake) still = fail?  Also don't want to encourage writing flaky tests.  

@stevekuznetsov I believe you have opinions on this.

**Comment by stevekuznetsov** [comment]
Yeah, we see two approaches:

 - needs to fail twice to fail the job: this reduces flake rate and increases merge rate but IMHO is only covering up bad tests. if we can determine the flake was due to infra, this is good
 - needs to fail only once to fail the job: this makes flakes that much more painful and should push people to fix them faster. if the flakes are in the infra, this is not useful

**Comment by spadgett** [comment]
@stevekuznetsov Our most common flake is the WebDriver flake (#1684), which I'd classify as infrastructure. We don't have too many flakes, so it hasn't been too much of an issue.
