### ISSUE TITLE
Pod summary has lots of repetition

### ISSUE THREAD

**Issue by smarterclayton** [openshift/origin-web-console#2433]
![image](https://www.dropbox.com/s/r07vj0hh7moq730/Screenshot%202017-11-02%2001.00.18.png?raw=1)

* Container names don't jump out (they look less important than the contents within them).
* Repeated mounts are just a blur of text - mounts probably should be nested under a single icon, with the path first (that's the thing that users see) then the content of what is mapped to it.  The problem with the config and secret names is that they don't have a ton of meaning, but the *types* and mount paths do
* Pod status is more important than the visual weight we give it.  Probably the most important thing on the page.
* Once we get to 2 or 3 containers, the two unaligned columns starts to be visually unappealing
* The two init containers message looks weird and out of place

From 3.7.0-alpha.1, not sure if any of this is addressed recently

**Comment by spadgett** [comment]
@openshift/team-ux-review

**Comment by jennyhaines** [comment]
@smarterclayton @spadgett @serenamarie125 - I'll work on designing this out to be more digestible since there is so much information. I'll create a high fidelity design that you could hopefully implement to simplify the UI a bit.

@smarterclayton - Could you send a screenshot of this in context within the rest of the screen, and make sure that it is of a "worst case scenerio" (includes as many different information types/datasets as possible)? Also, if there are any other instances of this type of information being shown in OpenShift on other screens, screenshots of those instances would also be very helpful in determining constraints in design. Thank you!

**Comment by spadgett** [comment]
@jennyhaines Here is a full page screenshot. This is from an actual build pod, so it's not even worst case or super uncommon.

![screenshot-2017-11-3 openshift web console](https://user-images.githubusercontent.com/1167259/32391359-24ebb966-c0a8-11e7-9d48-94baba75f0ff.png)

We use the same "pod template" styles on other pages.

**Comment by spadgett** [comment]
Other pages with pod templates:

![screen shot 2017-11-03 at 3 16 11 pm](https://user-images.githubusercontent.com/1167259/32391880-fb5a255e-c0a9-11e7-9444-758d1b19d0d3.png)

On the overview we show the pod template, but with less data:

![screen shot 2017-11-03 at 3 16 32 pm](https://user-images.githubusercontent.com/1167259/32391894-0a077bba-c0aa-11e7-9a0e-715a22843096.png)

**Comment by smarterclayton** [comment]
Prometheus is close to an upper bound:

page1:



page 2


page 3



page 4 omitted

**Comment by jennyhaines** [comment]
@smarterclayton @jwforres @spadgett @rhamilto @serenamarie125 - Please let me know whether you think I've addressed these issues.

I took a look at the Pod Summary screen design, realizing that any formatting changes made to the overall layout of the screen, or individual sections of it (like "Containers", "Init Containers", and "Volumes", would also affect other screens across OpenShift that display similar information. (Please visit here for the designs of some other affected screens, including Deployment Config Details screen, and Specific Deployment Details screen : [Google Drive Link](https://drive.google.com/drive/folders/1NkeJLE3f8atIBTVcNKgaimJzvRU6Bx81?usp=sharing)

**Current Implementation of Pod Summary:**
![current 2](https://user-images.githubusercontent.com/24898297/33900306-f9d03d6c-df3b-11e7-9771-a4666cffe3ad.png)

**After Design Changes:**
![pod details-successful](https://user-images.githubusercontent.com/24898297/33900687-6124a24a-df3d-11e7-80db-97051950e6f8.png)


## The larger changes that I've made to the Pod Summary Screen are listed out below:

- To allow the Container names to have the correct hierarchy, I nixed the "Templates" header, to bring all subsequent headers ("Containers", "Init Containers", and "Volumes") up a level, and thus bringing the Container names up in size, as well. This helps to create the correct hierarchy between Container names and their details.

- Instead of using repeating icons and text to specify "mounts", I nested multiple mounts under a single icon, with the path first, then the content of what is mapped to it. In instances where there is only one mount, the mount information should just be inline with the "Mount" descriptor and icon.

- To make sure that the Pod status is more apparent (not hidden), I pulled it into an inline notification style that would sit over the tabs. It has an increased visual weight, here, and looks like it applys directly to the specific Pod name. I've mocked up various status types ("Completed", "Failed", "Pending", and "Running"), and included them in that Google Drive link, above. (Note the color and icon differences for each.)

- I've formatted the screen content a little differently, having the details section span the full width, across the top, and then displaying Init Containers, and Containers on a left column, and the Volumes information on a right column, underneath. (Conveniently, in the case that there is no Init Contain information to display, the Container information takes the place of where the Init container section would be.) This layout actually effectively uses much more of the screen space available.

- Currently, the section that says "2 init containers completed successfully", appears under the details. I suggest (based on talking with Jessica, Sam, and Robb), that we scrap this section, and roll this information into the appropriate init containers. This way, all information about each init container (including their statuses) is consolidated together. 

- The little icon next to the Init container "State" would correspond to the actual state the init container is in. For example, if an init container is running, the "fa-refresh" icon would be displayed here. this icon would always be grey, unless the status is "Failed", in which the icon should be pf-red-100, instead of grey.
