### ISSUE TITLE
Declarative pipeline steps show success despite failure 

### ISSUE THREAD

**Issue by siamaksade** [openshift/origin-web-console#2509]
When using the declarative syntax of Jenkins pipeline, the steps after a failure show green:

<img width="479" alt="screen shot 2017-11-15 at 13 12 23" src="https://user-images.githubusercontent.com/1174934/32852663-b09e30e4-ca06-11e7-8946-fdd553d60f57.png">

```
pipeline {
  agent {
    label 'maven'
  }
  stages {
    stage('Build') {
      steps {
        git 'http://gogs:3000/gogs/openshift-task.git'
        sh "mvn install"
      }
    }
    stage('Test') {
      steps {
        sh "mvn test"
      }
    }
  }
}
```

**Comment by spadgett** [comment]
@siamaksade Do you mind pasting the JSON from the `openshift.io/jenkins-status-json` annotation on the build?

**Comment by spadgett** [comment]
Looks like it's reporting status SUCCESS for that stage.

```json
        {
            "_links": {
                "self": {
                    "href": "https://jenkins-pipeline.127.0.0.1.nip.io/job/pipeline-sample-pipeline/1/execution/node/11/wfapi/describe"
                },
                "log": null
            },
            "id": "11",
            "name": "Test",
            "execNode": "",
            "status": "SUCCESS",
            "error": null,
            "parameterDescription": null,
            "startTimeMillis": 1510773633668,
            "durationMillis": 646,
            "pauseDurationMillis": 0,
            "stageFlowNodes": [],
            "allChildNodeIds": []
        }
```

But the Jenkins UI doesn't show it as successful.

![1 2017-11-15 14-23-20](https://user-images.githubusercontent.com/1167259/32855725-943ec512-ca10-11e7-9d7c-925908bf62d5.png)

**Comment by spadgett** [comment]
I'm seeing different JSON when I look at the response from the Jenkins API when using Blue Ocean.

@bparees @gabemontero 

GET https://jenkins-pipeline.127.0.0.1.nip.io/blue/rest/organizations/jenkins/pipelines/pipeline-sample-pipeline/runs/1/nodes/

```json
[
   {
      "_class":"io.jenkins.blueocean.rest.impl.pipeline.PipelineNodeImpl",
      "_links":{
         "self":{
            "_class":"io.jenkins.blueocean.rest.hal.Link",
            "href":"/blue/rest/organizations/jenkins/pipelines/pipeline-sample-pipeline/runs/1/nodes/6/"
         },
         "actions":{
            "_class":"io.jenkins.blueocean.rest.hal.Link",
            "href":"/blue/rest/organizations/jenkins/pipelines/pipeline-sample-pipeline/runs/1/nodes/6/actions/"
         },
         "steps":{
            "_class":"io.jenkins.blueocean.rest.hal.Link",
            "href":"/blue/rest/organizations/jenkins/pipelines/pipeline-sample-pipeline/runs/1/nodes/6/steps/"
         }
      },
      "actions":[

      ],
      "displayDescription":null,
      "displayName":"Build",
      "durationInMillis":4040,
      "id":"6",
      "input":null,
      "result":"FAILURE",
      "startTime":"2017-11-15T19:20:29.580+0000",
      "state":"FINISHED",
      "causeOfBlockage":null,
      "edges":[
         {
            "_class":"io.jenkins.blueocean.rest.impl.pipeline.PipelineNodeImpl$EdgeImpl",
            "id":"11"
         }
      ]
   },
   {
      "_class":"io.jenkins.blueocean.rest.impl.pipeline.PipelineNodeImpl",
      "_links":{
         "self":{
            "_class":"io.jenkins.blueocean.rest.hal.Link",
            "href":"/blue/rest/organizations/jenkins/pipelines/pipeline-sample-pipeline/runs/1/nodes/11/"
         },
         "actions":{
            "_class":"io.jenkins.blueocean.rest.hal.Link",
            "href":"/blue/rest/organizations/jenkins/pipelines/pipeline-sample-pipeline/runs/1/nodes/11/actions/"
         },
         "steps":{
            "_class":"io.jenkins.blueocean.rest.hal.Link",
            "href":"/blue/rest/organizations/jenkins/pipelines/pipeline-sample-pipeline/runs/1/nodes/11/steps/"
         }
      },
      "actions":[

      ],
      "displayDescription":null,
      "displayName":"Test",
      "durationInMillis":0,
      "id":"11",
      "input":null,
      "result":"NOT_BUILT",
      "startTime":null,
      "state":"NOT_BUILT",
      "causeOfBlockage":null,
      "edges":[

      ]
   }
]
```

**Comment by spadgett** [comment]
I think this needs to be looked at in the sync plugin. There's nothing I see in the JSON annotation on the build that tells the console the stage wasn't successful.

**Comment by gabemontero** [comment]
Agreed @spadgett wrt sync plugin focus / investigation.

The reality is that declarative pipeline was just recently added to the openshift jenkins image and differences between it and the traditional/scripted pipeline are still being sorted out.

Given the status of declarative pipeline integration, one could argue on the bug vs. enhancement distinction.  Thoughts @bparees ?

**Comment by bparees** [comment]
bug.  an understandable bug (the ground moved under our feet) but a bug nonetheless.

**Comment by gabemontero** [comment]
sure thing ... my intent was to start investigating in the short term regardless; just thought the question could be asked and wanted to make sure we were all on the same page - thanks

**Comment by gabemontero** [comment]
So I've spent an afternoon poking around, and made some progress in better understanding the state of things.

Essentially, the base pipeline support lists stages that declarative pipelines skips (because of errors in another stage) as "successful", so things are working as designed :-)   As a confirmation, @csrwng noticed a similar presentation in some of the non-blueocean jenkins ui display of pipelines where stages that were skipped would report successful.

The metadata stored by the declarative pipelin plugin in the base pipeline data model is not accessible via the extentsion points in the base pipeline support that sync plugin uses (RunExt, StageExt, FlowNodeExt).

There are (not surprisingly I'm sure) tactical/short-term and "strategic"/long term changes we could make here.

short-term:  though I don't have it coded up yet, it appears I can "borrow" a small amount of code from the declarative pipeline plug to get at the metadata citing a stage has been skipped; if I'm correct, I can either "slightly massage" the current JSON format we exchange with the OpenShift UI, adding a new "SKIPPED" value for the status field which is currently marked "SUCCESS", or simply exclude the information like we did with original/scripted pipeline.

long-term: you may have gotten a hint of this from the json @spadgett posted earlier, but aside from "skipping" stages, there is a non-trivial amount of code in blueocean that composes the json noted above, which of course then drives their UI's presentation ... how close we want to keep up with blueocean in this space (meaning feature work on both the sync plugin and UI sides) are planning / prioritization type discussions we should probably do some due diligence on (even if the outcome is we don't try to keep up).
