### ISSUE TITLE
Log out should return the user to the login page

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#2530]
Currently if you log out you are taken to this fairly useless page:
![screen shot 2017-11-22 at 10 40 38 am](https://user-images.githubusercontent.com/8974593/33135884-b975db5c-cf71-11e7-998f-999b795fe77f.png)

The only viable action from this page is to return to the log in page. (The help menu is still available, and documentation works, but other actions lead back to the login screen.)

**Comment by jwforres** [comment]
That is because of several reasons, this is one https://github.com/openshift/origin-web-console/pull/2528#issuecomment-346392060

In an SSO environment the admin could set it up so that logout only logs you out of openshift but not out of your SSO, it's up to them. In that case if we sent you back through login we would just immediately log you back in to openshift, rendering logout useless.
