### ISSUE TITLE
Build logs stop streaming at some point

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin-web-console#2613]
If I have a multi-minute long build and leave a tab open following the build logs, I always end up with some of the logs, but they're cut off. If I refresh the page I get the full logs.

/cc @jwforres

**Comment by stevekuznetsov** [comment]
I do see the watches on `Build`s `BuildConfigs` and `Event`s get re-upped about every two minutes, but no new text in the log.

**Comment by jwforres** [comment]
I thought we upped the connection timeout for longlived connections to be
something like 10 min on most of our servers. Is this on CI system? There
are settings in the load balancer IIRC. Rewatching a ton of stuff (like on
overview) every two minutes is wasteful.

I believe it was intentional that we dont reestablish broken watch
connections for streamed content. Part of the issue is that we limit to a
certain number of lines (5000 I think). So if we refetched the log without
you asking us to then we are going to lose log you may have been actively
looking at.

I think the second issue is that we don't know the difference between the
log stream ending because the log is actually done versus the log stream
ending because the connection was closed by the ELB due to inactivity on
the TLS connection. Error codes on websockets are crap.

**Comment by stevekuznetsov** [comment]
@smarterclayton there was some load balancing shenanigans on the CI cluster -- could this be a symptom as well?
