### ISSUE TITLE
Improve modal consistency

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-console#2661]
* use of modal-header
  * use of modal-title
* background color
* button alignment (right) and button order (secondary then primary)
* close by clicking background
  * uibModal --> configurable, default is true
  * overlay-panel --> false

PatternFly modal:
![screen shot 2018-01-15 at 11 50 27 am](https://user-images.githubusercontent.com/895728/34953243-4f740280-f9ea-11e7-85b9-51a14c55aadd.PNG)

**Comment by spadgett** [comment]
Related to #659

**Comment by ncameronbritt** [comment]
Is the plan to move to the modal-overlay style? I think that's what we want.

**Comment by sg00dwin** [comment]
@ncameronbritt fyi


**Create webhook secret**
Click outside to close _NOT ENABLED_
![export-html_html_be4f5022684c0014](https://user-images.githubusercontent.com/1874151/35242744-7c7ed306-ff88-11e7-927f-7753cdf90a2d.png)

---

**Create source secret**
Click outside to close _NOT ENABLED_
![export-html_html_9f946fcfcbcae0c9](https://user-images.githubusercontent.com/1874151/35242371-6496eacc-ff87-11e7-91b1-3b15e6360f5a.png)

---

**Create image secret**
Click outside to close _NOT ENABLED_
![export-html_html_819f304541638654](https://user-images.githubusercontent.com/1874151/35242314-389e4460-ff87-11e7-8725-dac2d6c98a34.png)

---

**Inactivity logout alert**
Click outside to close _IS ENABLED_
![export-html_html_3408dc9a83164b8b](https://user-images.githubusercontent.com/1874151/35242263-0dc6de96-ff87-11e7-8891-9a17548f558a.png)

---


**Launch confirmation**
Click outside to close _NOT ENABLED_
![export-html_html_7b4020ebe6948280](https://user-images.githubusercontent.com/1874151/35242197-e3f659a2-ff86-11e7-99cd-8ac775c61ed0.png)



---

**Remove membership role**
Click outside to close _IS ENABLED_
![export-html_html_a9406f8e87eb7ede](https://user-images.githubusercontent.com/1874151/35241862-ecc3ca16-ff85-11e7-8315-5bdd7600ab7c.png)


---

**Debug terminal for container**
Click outside to close _NOT ENABLED_
![export-html_html_36e1b2b8d1c36469](https://user-images.githubusercontent.com/1874151/35241817-c1d9bbb2-ff85-11e7-9a2c-f4b41808c03b.png)

---

**Delete {something}**
Click outside to close _IS ENABLED_
![export-html_html_c31c8ee81f7981e7](https://user-images.githubusercontent.com/1874151/35241784-9f83b860-ff85-11e7-84cd-56955be95698.png)

---

**Cancel deployment**
Click outside to close _IS ENABLED_
![export-html_html_9dce51f9964b267](https://user-images.githubusercontent.com/1874151/35241760-865ec6a4-ff85-11e7-88bb-f5940e07f95d.png)


---

**Scale pods to zero**
Click outside to close _IS ENABLED_

![export-html_html_1896d8b1abbbe976](https://user-images.githubusercontent.com/1874151/35241730-6901168e-ff85-11e7-842f-97294a27c60f.png)


---

**Process or save template**
Click outside to close _NOT ENABLED_
Is their a reason this can’t be an additional step, instead of a modal on top of modal?

![export-html_html_e6cd3b54a1180b04](https://user-images.githubusercontent.com/1874151/35241658-1d792e22-ff85-11e7-8474-ce578fd8f53f.png)


---

**Set home page**
Click outside to close _NOT ENABLED_
![export-html_html_cfd4991106039dce](https://user-images.githubusercontent.com/1874151/35240928-ec41436e-ff82-11e7-9126-fa0db99cf38c.png)


---

**Save partial log**
![export-html_html_cf9ae3c4d5a9ccc3](https://user-images.githubusercontent.com/1874151/35240872-ce77b5de-ff82-11e7-8d1d-e83c0f273421.png)


---

**Jenkinsfile examples**
Click outside to close _IS ENABLED_

![export-html_html_8d089b6d529c4ff](https://user-images.githubusercontent.com/1874151/35240824-ae0ad240-ff82-11e7-977d-ce957bf60e22.png)

---

**Replace existing items**
Click outside to close _IS ENABLED_

![export-html_html_7a6d9d376c6ac0a0](https://user-images.githubusercontent.com/1874151/35239685-39a88bd4-ff7f-11e7-95a7-a0cfd5cee65b.png)

---

**Create Project**
Click outside to close _NOT ENABLED_
<img width="621" alt="screen shot 2018-01-22 at 3 29 41 pm" src="https://user-images.githubusercontent.com/1874151/35242928-27eb7244-ff89-11e7-85ea-a759886ba2cf.png">

**Comment by ncameronbritt** [comment]
@openshift/team-ux-review Here are the examples of the different modals that @sg00dwin has collected.

**Comment by beanh66** [comment]
@sg00dwin thanks for putting this together! We are taking a look today and will get back to you asap.

**Comment by beanh66** [comment]
@sg00dwin per the design review, we have come up with the following guidelines for all modals. These are consistent with PatternFly: 

1. Modals should not close when clicking away and the area behind modals should be dimmed. 
2. All modals should include: 
- a light grey header bar: 82px tall, and pf-black-150 (#f5f5f5) background color
- a title: 13px, 700 weight, spaced 36px from left edge and centered vertically
- an “X” to close the modal: “pficon-close”, 18px, #626262 default color, #191919 hover color, spaced 36px from right edge and centered vertically
3. The modal background color should be white.
4. Primary actions should be in the right corner. If secondary actions also exist, the should be to the left of the primary action.

**Comment by beanh66** [comment]
The above styles have been applied to a number of the modals shown in this issue. See attached for the new proposed designs:

![04-jenkinsfile](https://user-images.githubusercontent.com/18057044/35409336-e19a52d4-01df-11e8-9f9b-df2915650d29.png)

![05-set home page](https://user-images.githubusercontent.com/18057044/35409337-e1a44816-01df-11e8-8557-9aae4852ee01.png)

![06-partial log](https://user-images.githubusercontent.com/18057044/35409338-e1b6849a-01df-11e8-8209-02e8bfc653e7.png)

![08-create xyz form](https://user-images.githubusercontent.com/18057044/35409339-e1c300d0-01df-11e8-98e3-fccade6bc05b.png)

![09-debug container](https://user-images.githubusercontent.com/18057044/35409340-e1d33306-01df-11e8-86f4-fb94565cc077.png)

![03-add to application](https://user-images.githubusercontent.com/18057044/35409365-fa523242-01df-11e8-83cb-a37c6185e4cb.png)

![07-inactivity](https://user-images.githubusercontent.com/18057044/35409366-fa5b3b94-01df-11e8-8132-af900f4d6739.png)





:

**Comment by beanh66** [comment]
Note: We are suggesting a destructive button on the case below since text is being replaced. 
![10-replace existing](https://user-images.githubusercontent.com/18057044/35409399-16b4f8f2-01e0-11e8-851d-953d79bd89f2.png)

**Comment by beanh66** [comment]
Note: All destructive modals (Delete/ Remove/ Cancel/ End/ Replace, etc.) should follow the format below:
![1-destructive modal](https://user-images.githubusercontent.com/18057044/35409473-536d63ec-01e0-11e8-96eb-7c6936d5077d.png)

**Comment by beanh66** [comment]
@spadgett @sg00dwin I posted the proposed designs above for most modals mentioned. How should we handle the remaining items? Should we create separate issues for (1) the Import YAML modal on a modal and (2) Create Project popover? Let me know what works best.

**Comment by spadgett** [comment]
@beanh66 separate issues makes sense to me, thanks!

**Comment by rhamilto** [comment]
> Modals should not close when clicking away and the area behind modals should be dimmed.

I think an argument can be made that the "Jenkinsfile Examples" modal could be excepted from this rule since it's not really a blocking action and is more of a giant tooltip.  Agree/disagree?

**Comment by rhamilto** [comment]
> a light grey header bar: 82px tall ... spaced 36px from right edge and centered vertically

These values are actually 41px and 18px.  I'm guessing you took a screenshot on your retina monitor and measured from it since the values are exactly doubled?

**Comment by beanh66** [comment]
@rhamilto I'll defer to @jennyhaines on the values. Thanks for checking on it though! 

> I think an argument can be made that the "Jenkinsfile Examples" modal could be excepted from this rule since it's not really a blocking action and is more of a giant tooltip. Agree/disagree?

Per the comment above, I would rather us be consistent with the behavior so force the user to close a modal. If we don't want to force that action and this is a case where it's simply informative content, we could consider using the modaless overlay panel pattern here instead.

**Comment by sg00dwin** [comment]
@beanh66 After talking with @rhamilto there are 2 use cases above where it seems that allowing a "background click" to close the modal would be appropriate and we wanted to get your thoughts.  

[Inactivity session logout](https://user-images.githubusercontent.com/18057044/35409366-fa5b3b94-01df-11e8-8132-af900f4d6739.png) and the [What's a Jenkinsfile](https://user-images.githubusercontent.com/18057044/35409336-e19a52d4-01df-11e8-9f9b-df2915650d29.png).

**Comment by jennyhaines** [comment]
@rhamilto - I think I did just that with measuring spacing! Here are the edited guidelines:

All modals should include:

- a light grey header bar: 41px tall, and pf-black-150 (#f5f5f5) background color
- a title: 13px, 700 weight, spaced 18px from left edge and centered vertically
- an “X” to close the modal: “pficon-close”, 18px, #626262 default color, #191919 hover color, spaced 18px from right edge and centered vertically

**Comment by jennyhaines** [comment]
@beanh66 , FYI ^

**Comment by beanh66** [comment]
@sg00dwin I totally agree on the inactivity modal since a click anywhere should keep the user active. As far as the Jenkinsfile, we have an open story to improve the help throughout OpenShift anyways, so if it makes more sense, you can leave it as is and we can revisit it with the follow-up help story. I know there are others like this such as the "What are millicores" or "What are MiBs" links.

**Comment by beanh66** [comment]
There is a separate issue open for the create project modal: https://github.com/openshift/origin-web-console/issues/2725
