### ISSUE TITLE
No environment tab on vanilla replication controllers

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#277]
The environment tab only appears for deployments and not plain replication controllers. You should be able to view and edit replication controller environment variables.

I also suggest we make the deployment environment tab use a read only editor instead of the table for consistency with deployment configs.

/cc @jwforres

**Comment by benjaminapetersen** [comment]
So one issue here, I'm seeing the need to support the `valueFrom` instead of `value` for this.  Example:
```
[ { "name": "POD_NAMESPACE", "valueFrom": { "fieldRef": { "apiVersion": "v1", "fieldPath": "metadata.namespace" } } } ]
``` 
I don't believe we did that yet in the key-value-editor.  A fast fix is to drop in the `<environment>` directive to at least see the env vars as this supports `valueFrom`.

We've got a discussion rolling [here](https://github.com/openshift/angular-key-value-editor/issues/31) on some of this I think.

**Comment by benjaminapetersen** [comment]
Other quick notes: 
- if edited on an RC, it will not automatically redeploy.  User would have to scale down/scale up. 
- issues with the env vars not going on a DC instead (per jwforres comment on kve issue)?

**Comment by jwforres** [comment]
You should only let them edit env on an RC if it was not created by a
deployment config.

**Comment by benjaminapetersen** [comment]
Assuming that:
```javascript
// if i have a annotation for a dc, im good to edit, else no
deploymentConfigName = $filter('annotation')(deployment, 'deploymentConfig');
```
I'm good on that!
