### ISSUE TITLE
Delete project dialog no longer shows the name to type

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-console#2864]
Was this an intentional change?  You used to see the name in bold:

![screen shot 2018-03-01 at 10 11 50 am 1](https://user-images.githubusercontent.com/280512/36852197-187b983e-1d39-11e8-8c49-889fea0a2942.png)

@spadgett @rhamilto 

If this is expected, this issue can be closed.

**Comment by spadgett** [comment]
@benjaminapetersen The name is there.... Is the bug that it's no longer bolded?

**Comment by benjaminapetersen** [comment]
Right. not bold. and i think it was larger.  it was previously very clear & obvious what you should type to get the "delete" button to activate.  Memory might be foggy but i thought this modal was scarier.  😄

**Comment by spadgett** [comment]
@openshift/team-ux-review 

/bug usability
/priority p3
/assign @rhamilto

**Comment by rhamilto** [comment]
I believe the issues is because the all the text "Are you sure you want to delete the project 'My Project'?" is now bold now that it's part of the modal-title rather than a separate node within the content (it was an h1 with strong around the project name).  A possible fix would be to add the project name to the last sentence?

Type **My Project** to confirm deletion.

For reference, Github's looks like:
![screen shot 2018-03-01 at 10 29 27 am](https://user-images.githubusercontent.com/895728/36853082-7bac958c-1d3b-11e8-9669-3ab35a0d89f6.PNG)

**Comment by benjaminapetersen** [comment]
Yup. Github even used to be a bit more clear than that. Currently, ours is too much of a plain modal, it no longer feels like an "oh crap, better not screw this up" moment.

**Comment by beanh66** [comment]
@rhamilto I like your idea to change that last sentence to "Type **My Project** to confirm deletion."

**Comment by rhamilto** [comment]
Fixed by origin-web-common version bump in #2905
