### ISSUE TITLE
Which images streams tags are displayed in Deploy Image dialog

### ISSUE THREAD

**Issue by olaf-meyer** [openshift/origin-web-console#3031]
Hello,

I created an additional OpenShift project with custom base images. Via command line it is possible to list the image stream of the custom base images. However in the web-console I'm unable to see the project with my custom image streams in the dialog "Deploy Image". Do I need to add an annotation to the my project or image stream?

Thank you in advance.

**Comment by spadgett** [comment]
Are you logged in as the same user in the CLI and the web console? We should the list of projects that you have access to in the dropdown.

/kind question
/assign

**Comment by olaf-meyer** [comment]
Yes, I'm logged in with the same user. To get the images streams that I view I use the command "oc get is" on the CLI. However I don't have view permission for the base image project in which the imagestreams are stored. We don't want to change the permission of the project, because otherwise the base image project would become visible for all user. 

I don't have view permissions for the "OpenShift" project either. Is my assumption correct, that project "OpenShift"  hardcoded in the project selection?

**Comment by spadgett** [comment]
OK, yeah. This is a current limitation of the dialog. If you don't see the project in the project list, we don't know that you have authority to list image streams in the project. There's way for us to even know that the project exists using only the user's token.

It might be possible to make the dropdown editable so you could type the name. Or we could let admins add to the list for everyone.

The `openshift` namespace is hard-coded since it's a well-known shared namespace for image streams and templates.

/kind enhancement

**Comment by olaf-meyer** [comment]
Is this still relevant or should I close the issue?

**Comment by serenamarie125** [comment]
@christianvogt is this still an issue?  Thanks

**Comment by christianvogt** [comment]
@serenamarie125 the behavior today is still the same and we only list those available in the openshift namespace providing the user has permission to list them.
