### ISSUE TITLE
How to Troubleshoot OpenShift LDAP(active directory) Authentication

### ISSUE THREAD

**Issue by imranrazakhan** [openshift/origin-web-console#3089]
On login at web-console with ldap identityprovider i am getting error

`An authentication error occurred.`

Before configuring LDAP i verified connectivity with "ldapsearch", now i want to debug what goes to AD and what response openshift received.

I enabled debugging by editing below file and setting "`DEBUG_LOGLEVEL=4`"

`vi /etc/origin/master/master.env`

but i am unable to find anything in `/var/log/messages` or `master-logs api api`

##### Version

```
[root@xxx ~]# oc version
oc v3.10.0+0c4577e-1
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://xxx:8443
openshift v3.10.0+456651d-57
kubernetes v1.10.0+b81c8f8
```

##### Steps To Reproduce
login to webconsole

##### Current Result
Authentication failure

##### Expected Result
Authentication passed

##### Additional Information
I have configure multiple identityprovider and authentication with htpasswd is successful

**Comment by ghost** [comment]
Maybe this will be helpful.
https://docs.okd.io/3.10/install_config/web_console_customization.html#customizing-the-login-page
and
https://docs.okd.io/3.10/install_config/web_console_customization.html#customizing-the-oauth-error-page

**Comment by stewartshea** [comment]
@imranrazakhan 

Hi Imran, 

The ldap errors can be found in the api controller logs(`master-logs api api`). I was able to identify the following logs with DEBUG_LOGLEVEL=4. 

```
I1022 07:07:51.517261       1 ldap.go:129] searching for (&(memberOf:1.2.840.113556.1.4.1941:=cn=OCP_Users,CN=Users,DC=cloud,DC=lab)(sAMAccountName=administrator))
I1022 07:07:51.585054       1 ldap.go:146] found dn="CN=Administrator,CN=Users,DC=cloud,DC=lab" for (&(memberOf:1.2.840.113556.1.4.1941:=cn=OCP_Users,CN=Users,DC=cloud,DC=lab)(sAMAccountName=administrator))
I1022 07:07:51.659283       1 ldap.go:150] error binding password for "CN=Administrator,CN=Users,DC=cloud,DC=lab": LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580
```

The reconfiguration does require a restart of the service. If you run something like "ps -aux | grep openshift-master-api" you car verify the currently running loglevel.

**Comment by imranrazakhan** [comment]
@Shea Stewart
Thanks for updates, i have to do following to get it work

add in inventory file 
```
openshift_master_debug_level=5
debug_level=5
```

run
`ansible-playbook -i inventory-cns.ini /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml`

I think i have multi master environment and changing on one master was not working.

**Comment by stewartshea** [comment]
@imranrazakhan 
It can be difficult to troubleshoot across multiple masters for sure (which is why we often suggest forcing your client to route to a single master); one option is to leverage the EFK stack if it's deployed, or in my scenario I use a bastion host to run ansible across all hosts which allows me to query each host for any logs related to ldap across all master hosts. 

Interesting that loglevel 5 worked for you. 4 worked for me, and 5 doesn't seem documented [here](https://docs.openshift.com/container-platform/3.10/install_config/master_node_configuration.html#master-node-config-logging-levels). 

Anyways, thanks for adding your solution here as well :) Glad to hear you got through the issue.
