### ISSUE TITLE
The label filter isn't intuitive (to me at least)

### ISSUE THREAD

**Issue by danmcp** [openshift/origin-web-console#318]
The fact that it's one text box makes me think it's asking for a label value.  It might make it more obvious to make it multiple fields so you could be clear you were asking for a label name to start with and then an operator and then a value.

**Comment by spadgett** [comment]
@danmcp Can I ask what page you were using the label filter on? Would a plain "Filter by keyword" input would have worked better, or did you need to specifically filter on labels?

We've discussed moving away from the label filter in some places. Currently on the monitoring page, we use a plain keyword filter that seems to work well:

![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/17518511/311a5ab2-5e16-11e6-90ca-e4f45b423e5e.png)

**Comment by danmcp** [comment]
@spadgett I was on the the 3.2 overview.  Filter by keyword might have worked.  In this case I knew the key and the value.  But it wasn't obvious from the UI that I was even supposed to enter the 'key in value' until I typed and clicked around for a bit.  Actually 'in' might even be confusing for a lot of people.  Its fairly mathy.

**Comment by sg00dwin** [comment]
Perhaps changing the placeholder text to be more explanatory. 
_Filter by ... (label-name : label-value)_

<img width="675" alt="screen shot 2016-09-22 at 10 28 34 am" src="https://cloud.githubusercontent.com/assets/1874151/18752060/39670650-80af-11e6-9cee-a583f350e7dc.png">

ccing @rhamilto since he's currently reworking the markup & styling.

**Comment by rhamilto** [comment]
FYI @ncameronbritt
