### ISSUE TITLE
Webconsole Installing and Running an All-in-One Server

### ISSUE THREAD

**Issue by Kahuna26** [openshift/origin-web-console#3180]
Hi,

- install url: https://docs.okd.io/3.11/getting_started/administrators.html#installation-method

After installing the All-in-One Server i get the error below while trying to access the console:

```
"message": "forbidden: User "system:anonymous" cannot get path "/console": no RBAC policy matched",
```

The documentation suggested that a console should be available after the install guide. (just like the all-in-one-server1.4.*)
Am i missing some steps or is this part removed?

**Comment by spadgett** [comment]
Hi, unfortunately running OpenShift this way does not install the web console since it is no longer part of the master. It now runs as a pod on the platform. You'll need to use `oc cluster up` instead.

https://github.com/openshift/origin/blob/release-3.11/docs/cluster_up_down.md

This appears to be a documentation bug in 3.11 since console does not support this method of starting OpenShift.

@ahardin-rh FYI the line that says "starts the web console listening on all interfaces at /console (0.0.0.0:8443)" in the above link is no longer accurate.
