### ISSUE TITLE
Need to update descriptions for build config change trigger

### ISSUE THREAD

**Issue by jwforres** [openshift/origin-web-console#321]
Build config change triggers don't work the same way that DC config change triggers do.  This is intentional in the API and not expected to change soon.  BC config change triggers only designate whether a build should be created when the BC is first created.  So we need to update the checkboxes on the BC editor (and new-app?)

**Comment by spadgett** [comment]
Should we remove the checkbox from the edit build config page entirely? Based on the description from @jwforres, it won't do anything since the build config already exists.

**Comment by jhadvig** [comment]
+1 for removing the checkbox entirely.. no point to have it there.. would just confuse users.. and me as well :smile:

**Comment by jwforres** [comment]
good point.  @bparees said eventually it may do what we thought it did, we
can add it back when it does, so just give us some warning when you change
the behavior @bparees

**Comment by jhadvig** [comment]
Closing this one due to https://github.com/openshift/origin-web-console/pull/298 where we:

- removed the confgiChange trigger checkbox from BC editor
- reword the configChange trigger chackbox in the fromImage create flow to `Launch the first build when the build configuration is created`

@jwforres fyi
