### ISSUE TITLE
Metrics charts should not require samples every 30s

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#349]
To calculate CPU and network usage rates, we require that heapster sample at least every 30s for a one hour chart. We should look at using Hawkular's rate APIs or getting the raw metrics data from Hawkular to remove this limitation.

We might want to make the time ranges customizable as well. For instance, if Hawkular is configured to keep metrics for fewer than 7 days, we shouldn't show the 7 days option in the time range dropdown.

/cc @mwringe @smarterclayton @DirectXMan12

**Comment by DirectXMan12** [comment]
In addition to the current `cpu/usage` metric (what's being used now, and is cumulative), Heapster now exports the `cpu/usage_rate` metric (and a similar metric for network, IIRC), which is a rate metric.  Instead of calculating the rate from the cumulative `cpu/usage` metric, you should be able to just ask Hawkular for the `cpu/usage_rate` metric directly.  This has the added benefit of ensuring that what users see from Heapster and what users see from Hawkular match up exactly (there were previously slight discrepancies due to time frames).

**Comment by mwringe** [comment]
+1 to using the cpu/usage_rate that the newer Heapster version provide. That should make things easier.

**Comment by spadgett** [comment]
@DirectXMan12 thanks, are there rate metrics for network sent/received as well?

**Comment by DirectXMan12** [comment]
yep `network/tx_rate` and `network/rx_rate`.

**Comment by spadgett** [comment]
Perfect, we need to be using these. Thanks.
