### ISSUE TITLE
Top level bar redesign

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/origin-web-console#46]
Hi,
I find it difficult to think that the ? icon has important things to show. I would rather have some top level items, and then maybe some in dropdown, like this console (at the bottom in this case):

![1_ha](https://cloud.githubusercontent.com/assets/78350/15605855/e3deb24e-2408-11e6-9c3d-288255ec1d65.png)

- Download the client as top level, with drop down to different platforms:
- Documentation link
- Submit an issue link
- And about (where we could add release notes) and make easy to extend

**Comment by spadgett** [comment]
Having top-level navigation along **both** the top and sides seems confusing. The application you show as an example doesn't have any vertical navigation, so doesn't have that problem. I also think it would be strange if most of the top level nav items take you completely out of the console.

We're following the Patternfly guidelines for vertical navigation.

https://www.patternfly.org/patterns/vertical-with-persistent-secondary/

We do have a card to improve navigation in the web console. I think that is the best place to discuss since there is already design work underway.

https://trello.com/c/dWIKyBWi

If the issue is that the CLI download is not discoverable, there might be other ways to improve that. For instance, having a link to the CLI in the empty state page for a project or on the all projects page.

**Comment by jorgemoralespou** [comment]
Nope, the issue is not only CLI not being discoverable, but having more items in top navigation. 
And you can argue that you don't have top navigation (or whatever you wanna call it) but there's a top bar with links that could be there, in top level, instead of hidden in a drop down in an ? icon.

I would like some links to be always visible in every page displayed.

So maybe instead of 1 single icon with dropdown for 3 topics, 3 icons with direct access to those topics.

**Comment by sspeiche** [comment]
I think we should just put this feedback in the Trello card addressing navigation. We also have cards to put status notifications in the top bar, for example: "Your account will expire in 7 days".

Doing a survey, very web based product does it a little differently and it comes down to a matter of style or preference. I'd suggest we even go so far as wait to get more end sure feedback on it.

**Comment by jwforres** [comment]
As mentioned this discussion can continue in the trello card
