### ISSUE TITLE
Monitoring page filter doesn't line up with dropdown at mobile widths

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#543]
![openshift_web_console](https://cloud.githubusercontent.com/assets/1167259/18594163/94224390-7c0c-11e6-9e64-74a60e9087e4.png)

/cc @sg00dwin @jwforres @rhamilto

**Comment by rhamilto** [comment]
Fixing this bug is trivial, and I've got a fix.  However, I'm wondering if we shouldn't change the presentation so it matches the other two similar contexts.

![screen shot 2016-09-16 at 2 23 46 pm](https://cloud.githubusercontent.com/assets/895728/18596887/65a4c12a-7c19-11e6-96e9-8ee7756d809e.PNG)

![screen shot 2016-09-16 at 2 23 24 pm](https://cloud.githubusercontent.com/assets/895728/18596890/695de3e6-7c19-11e6-9255-0f8a88278e6a.PNG)

@jwforres, @spadgett:  any objections to making Monitoring consistent with Events and Other Resources?

**Comment by sg00dwin** [comment]
+1

**Comment by jwforres** [comment]
you mean that the filter box doesn't go full-width at mobile? if so then
yes go for it

**Comment by spadgett** [comment]
+1 to stacking the controls at mobile.

**Comment by rhamilto** [comment]
Fixed by 549
