### ISSUE TITLE
Project > Browse > Other Resources > Template shows only templates for that project

### ISSUE THREAD

**Issue by ALRubinger** [openshift/origin-web-console#62]
Ben notes that the user actually has access to templates in other projects that you have view rights on; might be nice to have a comprehensive view of all templates at the user's disposal.

Not critical.

**Comment by jwforres** [comment]
This is intentional, you are within the scope of a project, so these are only resources within your project.  

When are you wanting to view all templates available to you, when you are trying to create from a template?  We have plans to make significant improvements to the "Add to Project" flow and its been at least mentioned that we could let you select templates from any project you have access to.  But today you may have access to list templates in a project but not have view access to the project itself (e.g. the openshift namespace).  So even then its not 100% accurate.

**Comment by ALRubinger** [comment]
Cool; in the discussion we mentioned we might raise it; leaving to you to decide the course of action.

**Comment by spadgett** [comment]
@ALRubinger I think users will benefit from seeing these on the Add to Project page, which is part of the redesign in https://trello.com/c/xlQaSaxT. Is there a particular scenario you had in mind for browse -> other resources?

I worry it might be confusing if we do this for templates and not other kinds.

**Comment by ALRubinger** [comment]
Would love to get into this in July-ish, but the thing I found a bit confusing was that there were actually templates I did have the right to apply to the project, but because they weren't associated with the project were not in view.  Before advocating any particular course of action I'd need to fundamentally understand all the domain concerns and also the work you've already got planned in the "Add to Project" flows. :)

**Comment by jwforres** [comment]
Moving this to trello https://trello.com/c/NFhQawHD
