### ISSUE TITLE
How to load an external config.js file for extensions-app

### ISSUE THREAD

**Issue by sub-mod** [openshift/origin-web-console#710]
Hi
What is the right pattern to load an external config.js file for the extensions-app?
If I add the config.js as extensions then every change in config will need openshift-master restart.
I was wondering whether I can load the config.js from filesystem?
Which approach is recomended?

**Comment by spadgett** [comment]
@sub-mod I'd add a JSON file as a static file, then request it when your extension loads.

https://docs.openshift.org/latest/install_config/web_console_customization.html#serving-static-files

You should get a new version when the file changes on the filesystem without needing to restart master.

**Comment by jwforres** [comment]
How often are you expecting your config to change?  We've already established the pattern that changes to configuration require the master to be restarted.  Also what kind of configuration is it you need? Because we have something called extensionProperties that you can define in the master-config https://docs.openshift.org/latest/install_config/master_node_configuration.html#master-config-asset-config

**Comment by jwforres** [comment]
@sub-mod can this be closed?

**Comment by jwforres** [comment]
closing due to lack of response, if you have more questions on this please re-open
