### ISSUE TITLE
Have to press tabs twice to switch on iOS

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#811]
I suspect the latest Patternfly added a hover style to the tabs, making it so I have to press twice.

/cc @rhamilto @jwforres

**Comment by spadgett** [comment]
This Patternfly style seems to be the culprit:

https://github.com/patternfly/patternfly/blob/64357c539ed7f8723f5dfe5b2c8680f869246cf6/src/less/mixins.less#L84-L94

**Comment by rhamilto** [comment]
The hover style isn't new to PatternFly tabs, so my guess is we simply didn't notice this before? If I'm not mistaken, Mobile Safari has always translated :hover to (first) click in order to accommodate things like hover-activated dropdowns, etc.

It appears we could utilize touch detection and disable hover for things like tabs, etc. http://stackoverflow.com/a/25837326  I'm not sure it's worth the effort?
