### ISSUE TITLE
Inconsistencies between build and deploy pages

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin-web-console#880]
Perhaps a minor thing, though it is interesting that the build configuration page is structured as:

* Summary
* Configuration
* Environment
* (doesn't include events)

But the deployment configuration page is structured as:

* Details
  * (includes configuration)
* Environment
* Events

Seems like it would make sense to follow the same pattern from both. For example, if I'm looking for **Triggers** I need to look in different sections.

**Comment by spadgett** [comment]
The easy fix is to just have "Deployments" and "Builds" tabs as the first tab on each, then have a separate configuration tab. This also keeps the deployments table on screen. When it was below the config, it was off screen and easy to miss entirely.

We probably want the same "Latest deployment..." message as we have for builds.

I don't believe we have events for build configs, which is why there's no tab. Maybe we could get clever and show build pod events.

@jwforres @sspeiche @ajacobs21e opinion?

<img width="872" alt="screen shot 2016-12-13 at 10 38 12 am" src="https://cloud.githubusercontent.com/assets/1167259/21146646/6bc4ce6e-c120-11e6-857c-a2f6f4c9620d.png">

<img width="790" alt="screen shot 2016-12-13 at 10 38 43 am" src="https://cloud.githubusercontent.com/assets/1167259/21146654/700a395a-c120-11e6-92a9-4b30c3bc32c4.png">

**Comment by sspeiche** [comment]
I like it like this. Having builds and deployments under Configuration has sometimes been pushed off the visible screen. Having them like you show as their own tab, it is clear and better usage of smaller screens. Though if you have a large screen and only 2 builds say, it might be nice to have config + builds. I'd lean towards what you've done here for consistency and scaling for larger datasets.
